name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Create Release
        uses: rymndhng/release-on-push-action@master
        id: release
        with:
          bump_version_scheme: norelease # We will manage versioning via pull request labels: release:major, release:minor or release:patch
          tag_prefix: "v"
          use_github_release_notes: true

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"