name: PR e2e test on GCP

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      # - '.github/**'
      - '**.md'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  e2e:
    runs-on: janus-go-e2e
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -v ./...