name: Test e2e on GCP

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 1 || 0 }} # https://github.com/tj-actions/changed-files?tab=readme-ov-file#usage-
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          matrix: true
          files_ignore: |
            .github/**
            **.md
      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

  e2e:
    runs-on: janus-go-e2e
    if: ${{ needs.changed-files.outputs.matrix != '[]' }}
    needs: changed-files
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Build
        run: go build -o janus-go -v ./...

      - name: Run directly
        shell: bash
        env:
          AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
        run: ./janus-go -rolearn $AWS_IAM_ROLE_ARN > /dev/null

      - name: Run directly with sts region
        shell: bash
        env:
          AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
        run: ./janus-go -rolearn $AWS_IAM_ROLE_ARN -stsregion us-east-1 > /dev/null

      - name: Run directly with sts region and double dash params
        shell: bash
        env:
          AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
        run: ./janus-go --rolearn $AWS_IAM_ROLE_ARN --stsregion us-east-1 > /dev/null

      - name: Run with aws-cli
        run: aws --profile janus-go-e2e-gcp s3 ls