name: Release

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: wangyoucao577/go-release-action@v1
      env:
        CGO_ENABLED: 0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "janus"
        compress_assets: "OFF"
        ldflags: >-
          -s -w
          -X janus/types.Version=${{ github.event.release.tag_name }}
          -X janus/types.Commit=${{ github.sha }}
          -X janus/types.Date=$(date -u +%Y-%m-%d)
        build_flags: "-trimpath"
